name: Build/Release AstroDesk
on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This tells GitHub to start a Windows machine AND a Mac machine
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
